### ISSUE TITLE
Azure Github Deployment Issue with Umbraco 8

### ISSUE THREAD

**Issue by tetz2442** [umbraco/Umbraco-SqlServerCE#1] opened 2019-03-11 16:49 UTC
I was having an issue with deploying via github on an azure app with a new Umbraco 8 project. What ended up fixing it was adding a namespace to the Umbraco.SqlServerCE.targets file ` xmlns="http://schemas.microsoft.com/developer/msbuild/2003"`. The project tag ended up looking like this `<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

Once that was in place it deployed without a problem.

**Comment by tigreye007** [comment] 2019-03-11 17:19
To expand on this, MSBuild was failing with the following error, which is what led to the suggested fix:

D:\home\site\repository\packages\Umbraco.SqlServerCE.4.0.0.1\build\Umbraco.SqlServerCE.targets(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by zpqrtbnk** [comment] 2019-03-11 17:33
This error *seems* to be reported when ppl are using the package in a pre-VS2017 environment. I don't know how your pipeline is set, but can you ensure you are using the VS2017 MSBuild environment? Azure DevOps wants it to be "Hosted VS2017".

**Comment by tigreye007** [comment] 2019-03-11 17:49
@zpqrtbnk To reproduce, you can run the following command from the command prompt:  "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\Path\To\Umbraco.csproj"

**Comment by zpqrtbnk** [comment] 2019-03-11 19:31
The `14.0` in that command prompt path would indicate MS Build 14.0 which came with VS2015, whereas v8 require VS2017 ie MsBuild 15.0.

**Comment by tetz2442** [comment] 2019-03-11 19:43
I'm not really familiar with how the build process works in azure when using Github as the deploy source, but how would you change anything there in regards to the MS Build? I think if you add the namespace to that file I mentioned, then the issue with the azure deploy would go away. That is how we fixed it, at least temporarily

**Comment by zpqrtbnk** [comment] 2019-03-11 20:25
I have no idea how to fix the pipeline you use, unfortunately. Sure, adding that namespace would fix your problem, but I am afraid it would hide other problems. We do not support building v8 sites with MSBuild 14, and require MSBuild 15, because of some issues 14 has with framework 4.7.2 and netstandard packages. 

Which means... I am slightly afraid that adding that namespace... will lead you to *another* issue, etc.

Making sense?

**Comment by zpqrtbnk** [comment] 2019-03-18 08:23
Going to close this issue, but feel free to raise a new one if you are not happy about this? And, should you need to do it, could you raise it on the Umbraco Cms [GitHub tracker](https://github.com/umbraco/Umbraco-CMS/issues) as that would be more convenient for us? Thanks.

**Closed as completed by zpqrtbnk** 2019-03-18 08:23 UTC

**Comment by johnsonp57** [comment] 2019-03-26 15:34
I had to apply the same fix - this was also deploying to Azure App service from Bitbucket.  It seems that the default build server (Kudu) is still set up to use 14.0, unless you amend the default deploy.cmd file.  See https://github.com/projectkudu/kudu/issues/2350
